function hprms = mansearch()
    batchSize = 100;
    N = [900 0 100]; % training, validation and test
    gtzanDataSet = prepGTZAN(batchSize, N);
    
    hprms(1) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'GRU', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 10}},....
        'BN',                   [false false],...
        'dropRate',          	[0.0 0.0],...
        'clipping',          	[0 0],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );

    hprms(2) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'GRU', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 10}},....
        'BN',                   [false false],...
        'dropRate',          	[0.0 0.0],...
        'clipping',          	[30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );
    
    hprms(3) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'GRU', 'SoftmaxLayer'}},...
        'unitNum',              {{40 256 10}},....
        'BN',                   [false false],...
        'dropRate',          	[0.0 0.5],...
        'clipping',          	[30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );

    hprms(4) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'GRU', 'GRU', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 128 10}},....
        'BN',                   [false false false],...
        'dropRate',          	[0.0 0.0 0.0],...
        'clipping',          	[30 30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );
    
    hprms(5) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'GRU', 'GRU', 'SoftmaxLayer'}},...
        'unitNum',              {{40 512 256 10}},....
        'BN',                   [false false false],...
        'dropRate',          	[0.0 0.5 0.5],...
        'clipping',          	[60 30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );

    hprms(6) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'LSTM', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 10}},....
        'BN',                   [false false],...
        'dropRate',          	[0.0 0.0],...
        'clipping',          	[0 0],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );

    hprms(7) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'LSTM', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 10}},....
        'BN',                   [false false],...
        'dropRate',          	[0.0 0.0],...
        'clipping',          	[30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );
    
    hprms(8) = struct(...
        'dataSet',              {gtzanDataSet},...
        'type',                 {{'LSTM', 'LSTM', 'SoftmaxLayer'}},...
        'unitNum',              {{40 128 128 10}},....
        'BN',                   [false false false],...
        'dropRate',          	[0.0 0.0 0.0],...
        'clipping',          	[30 30 30],...
        'gdoa',                 'rmsProp',...
        'gdoaPrm',              [0.01 0.9 1e-8],...
        'gpumode',              false,...
        'batchSize',            batchSize,...
        'T',                    80,...
        'epochs',               50,...
        'noUpdatSpanCriterion', 10,...
        'longTerm',             false...
    );
end

%{
'rmsProp',  [0.01 0.9 1e-8]
'adaDelta', [0.95 1e-6]
'adaGrad',  [0.1 1e-8]
'adam',     [1e-3 0.9 0.999 1e-7]
%}

%{
hprms(1) = struct(...
    'type',                 {{'LSTMP', 'SoftmaxLayer'}},...
    'BN',                   [false false],...
    'dropRate',          	[0.0 0.0],...
    'clipping',          	[0 0],...
    'gdoa',                 'rmsProp',...
    'gdoaPrm',              [0.01 0.9 1e-8],...
    'gpumode',              false,...
    'batchSize',            3,...
    'unitNum',              {{2 {20 5} 3}},....
    'T',                    30,...
    'epochs',               50,...
    'noUpdatSpanCriterion', 10,...
    'longTerm',             false...
);
%}

%getDataSet = @() prepTestData(batchSize, 'testdata.mat');
%getDataSet = @() prepTestData(batchSize, 'C:\Users\yuto\Documents\MATLAB\data\gtzan\gtzanMFCC.mat');