function hprms = mansearch()
    home = userpath;
    home = home(1:end-1);
    patch = 120;
    
    hprms(1) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.9,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/gtzanMFCC.mat')),...     
        'patch',          patch...
    );

    hprms(2) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.9,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/gtzanMFCC.mat')),...     
        'patch',          patch...
    );

    hprms(3) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.9,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/gtzanMFCC.mat')),...     
        'patch',          patch...
    );
end

%dataPrep,      @(x) prepTrajectory();

%% notes
% 'units'       : mcell, bmcell, smax are applicable
% 'mcell'       : memory cell of LSTM
% 'bmcell'      : memory cell of bidirectional LSTM
% 'smax'        : softmax unit
% 'optimization': vanilla, rmsprop, adadelta are applicable
%% TBD
% Hessian-free optimization with conjugate gradient
% Lp units as deep output layers