function hprms = modeler()
    home = userpath;
    home = home(1:end-1);
    
    hprms(1) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         50,...
        'drate',          0.90,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/MFCC_data.mat')),...     
        'patch',          70 ...
    );

    hprms(2) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.95,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/MFCC_data.mat')),...     
        'patch',          70 ...       
    );

    hprms(3) = struct(...
        'nhid',           {{128 10}},....
        'units',          {{'mcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      20,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.90,...
        'droprate',       [1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/MFCC_data.mat')),...     
        'patch',          70 ...      
    );

    hprms(4) = struct(...
        'nhid',           {{[128 128] [128 128] 10}},....
        'units',          {{'bmcell','bmcell','smax'}},...
        'optimization',   'rmsprop',...
        'batchSize',      100,...
        'baselr',         0.01,...
        'epochs',         25,...
        'drate',          0.90,...
        'droprate',       [1.0 1.0 1.0],...
        'gcheck',         false,...        
        'dataPrep',       @(x) prepMFCC(strcat(home,'/data/gtzan/MFCC_data.mat')),...     
        'patch',          70 ...      
    );
end

%dataPrep,      @(x) prepTrajectory();

%% notes
% 'units'       : mcell, bmcell, smax are applicable
% 'mcell'       : memory cell of LSTM
% 'bmcell'      : memory cell of bidirectional LSTM
% 'smax'        : softmax unit
% 'optimization': vanilla, rmsprop, adadelta are applicable
%% TBD
% Hessian-free optimization with conjugate gradient
% Lp units as deep output layers